spring:
  config:
    activate:
      on-profile: prod
    import: aws-parameterstore:/cloud-app/prod/

  cloud:
    aws:
      region:
        static: ap-northeast-2

      parameterstore:
        enabled: true

      s3:
        bucket: camp-health-rmsb6752-files

  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate

management:
  info:
    env:
      enabled: true

info:
  app:
    message: ${team.name}