logging:
  level:
    root: INFO
spring:
  application:
    name: cloud-architecture

  jpa:
    show-sql: true
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB

management:
  endpoints:
    web:
      exposure:
        include: "*"