spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://my-database-cloud.cre282q4sdq2.ap-northeast-2.rds.amazonaws.com:3306/cloud
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: 12345678

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
