logging:
  level:
    root: INFO
spring:
  application:
    name: cloud-architecture

  jpa:
    show-sql: true
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health